name: OSDK v1.22.0

on:
  push:
    paths:
      - 'v1.22.0/**'
      - 'Dockerfile'

jobs:
  build-container-image:
        uses: ./.github/workflows/build-image.yaml
        with:
          osdk_version: 1.22.0
          registry: quay.io
        secrets: inherit