name: build-image

on:
  workflow_call:
    inputs:
      osdk_version:
        required: true
        type: string
    
      registry:
        type: string
        required: true
    
    secrets:
      REGISTRY_USERNAME:
        required: true
    
      REGISTRY_TOKEN:
        required: true
    
env:
  REGISTRY: ${{ inputs.registry }}
  OSDK_VERSION: ${{ inputs.osdk_version }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: quay.io/remote-dev/osdk-ansible-vscode:latest
          context: ./v${{ inputs.osdk_version }}
          file: ./Dockerfile
          build-args: |
             OPERATOR_SDK_VERSION=${{ inputs.osdk_version }}
           
           