name: OSDK v1.18.1

on:
  push:
    paths:
      - 'v1.18.1/**'
      #- 'Dockerfile'

jobs:
  build-container-image:
        uses: ./.github/workflows/build-image.yaml
        with:
          osdk_version: 1.18.1
          registry: quay.io
        secrets: inherit
        
        

  
    
