name: OSDK v1.18.1

on:
  push:
    paths:
      - "./v1.18.1/*"

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build image.
        uses: ./.github/workflows/build-image.yaml
        with:
          osdk_version: 1.18.1
        secrets: inherit
        
        

  
    
